# Firebird SQL Queries Library

# Metadata Queries
QUERY_TABLES = """
    SELECT TRIM(RDB$RELATION_NAME) AS TABLE_NAME
    FROM RDB$RELATIONS
    WHERE RDB$SYSTEM_FLAG = 0 
    AND RDB$VIEW_BLR IS NULL
    ORDER BY RDB$RELATION_NAME
"""

QUERY_VIEWS = """
    SELECT TRIM(RDB$RELATION_NAME) AS VIEW_NAME
    FROM RDB$RELATIONS
    WHERE RDB$SYSTEM_FLAG = 0 
    AND RDB$VIEW_BLR IS NOT NULL
    ORDER BY RDB$RELATION_NAME
"""

QUERY_PROCEDURES = """
    SELECT TRIM(RDB$PROCEDURE_NAME) AS PROCEDURE_NAME
    FROM RDB$PROCEDURES
    WHERE RDB$SYSTEM_FLAG = 0
    ORDER BY RDB$PROCEDURE_NAME
"""

QUERY_TRIGGERS = """
    SELECT TRIM(RDB$TRIGGER_NAME) AS TRIGGER_NAME
    FROM RDB$TRIGGERS
    WHERE RDB$SYSTEM_FLAG = 0
    ORDER BY RDB$TRIGGER_NAME
"""

QUERY_TABLE_COLUMNS = """
    SELECT 
        TRIM(r.RDB$FIELD_NAME) AS FIELD_NAME,
        f.RDB$FIELD_TYPE AS FIELD_TYPE,
        f.RDB$FIELD_LENGTH,
        r.RDB$NULL_FLAG,
        r.RDB$DEFAULT_SOURCE
    FROM RDB$RELATION_FIELDS r
    JOIN RDB$FIELDS f ON r.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
    WHERE TRIM(r.RDB$RELATION_NAME) = ?
    ORDER BY r.RDB$FIELD_POSITION
"""

# Activity Queries (Assuming DK$OPERATIONLOG exists as per user input)
QUERY_RECENT_ACTIVITY = """
    SELECT FIRST 100
        TRIM(TABLA) AS TABLA,
        OPERACION,
        TRIM(USUARIO) AS USUARIO,
        FECHA,
        1 AS NUM_OPERACIONES
    FROM DK$OPERATIONLOG
    ORDER BY FECHA DESC
"""

QUERY_ACTIVITY_SUMMARY = """
    SELECT 
        TRIM(TABLA) AS TABLA,
        COUNT(*) AS TOTAL_OPS,
        MAX(FECHA) AS ULTIMA_FECHA
    FROM DK$OPERATIONLOG
    GROUP BY TABLA
    ORDER BY TOTAL_OPS DESC
"""

# Duplicate Detection Queries
QUERY_DUPLICATES_EXACT = """
    SELECT 
        a.CODIGO,
        a.NOMBRE,
        (SELECT COUNT(*) FROM ARTICULO b 
         WHERE UPPER(TRIM(b.NOMBRE)) = UPPER(TRIM(a.NOMBRE))) as TOTAL_DUPLICADOS
    FROM ARTICULO a
    WHERE EXISTS (
        SELECT 1 FROM ARTICULO b
        WHERE UPPER(TRIM(b.NOMBRE)) = UPPER(TRIM(a.NOMBRE))
        AND b.CODIGO <> a.CODIGO
    )
    AND a.NOMBRE IS NOT NULL
    ORDER BY TOTAL_DUPLICADOS DESC, a.NOMBRE
"""

# General Stats
QUERY_STATS_ARTICULO = """
    SELECT 
        COUNT(*) as TOTAL_ARTICULOS,
        COUNT(DISTINCT CODFAMILIA) as TOTAL_FAMILIAS,
        AVG(PRECIOVENTA) as PRECIO_PROMEDIO,
        MIN(PRECIOVENTA) as PRECIO_MINIMO,
        MAX(PRECIOVENTA) as PRECIO_MAXIMO
    FROM ARTICULO
"""
